### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by flumf** [CaptainHorse/MAS-Additions#1]
thanks.

**Comment by DatCaptainHorse** [comment]
Soon™

**Comment by flumf** [comment]
oh okay
understandable i suppose

**Comment by DatCaptainHorse** [comment]
I just tested things yesterday and today, doesn't seem to be possible due to current Python/CPython limitations, sorry about this. I'll keep the issue open as a reminder, if one day Python actually wants to work with me I will update this issue.

**Comment by DatCaptainHorse** [comment]
Upcoming release will have Linux version (minimum required distro is from 2020 such as Debian 10)
Closing this (at last).
