### ISSUE TITLE
Removed links to this submod from MAS GitHub

### ISSUE THREAD

**Issue by multimokia** [CaptainHorse/MAS-Additions#10]
Just notifying you I have redacted links to this submod as it's out of date and breaks people's games.
![image](https://user-images.githubusercontent.com/22531674/91214950-cb3ca200-e6e1-11ea-9223-1aff10f7a613.png)

If you do update this again, feel free to add the link back, but until then any and all will be removed as it's becoming a tech-support nightmare.

**Comment by DatCaptainHorse** [comment]
Yeah, sorry for the trouble the submod has caused. I've only managed to recently fix up my computer and it's still showing issues, my own mental health isn't getting better either, demotivating me from doing anything.
