### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by okdsf** [CaptainHorse/MAS-Additions#12]
How can I solve this problem?

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Additions/zz_additions_face_detection.rpy", line 1, in script
    ﻿init 10 python:
  File "game/Additions/zz_additions_face_detection.rpy", line 5, in <module>
    registerAddition("SEAS", "Super Experimental Additions", "0.1.8")
NameError: name 'registerAddition' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Additions/zz_additions_face_detection.rpy", line 1, in script
    ﻿init 10 python:
  File "C:\Users\24255\Desktop\monika after story123\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\24255\Desktop\monika after story123\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Additions/zz_additions_face_detection.rpy", line 5, in <module>
    registerAddition("SEAS", "Super Experimental Additions", "0.1.8")
NameError: name 'registerAddition' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.12.0

**Comment by okdsf** [comment]
> How can I solve this problem?
> 
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> File "game/Additions/zz_additions_face_detection.rpy", line 1, in script
> ﻿init 10 python:
> File "game/Additions/zz_additions_face_detection.rpy", line 5, in
> registerAddition("SEAS", "Super Experimental Additions", "0.1.8")
> NameError: name 'registerAddition' is not defined
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
> File "game/Additions/zz_additions_face_detection.rpy", line 1, in script
> ﻿init 10 python:
> File "C:\Users\24255\Desktop\monika after story123\renpy\ast.py", line 814, in execute
> renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
> File "C:\Users\24255\Desktop\monika after story123\renpy\python.py", line 1719, in py_exec_bytecode
> exec bytecode in globals, locals
> File "game/Additions/zz_additions_face_detection.rpy", line 5, in
> registerAddition("SEAS", "Super Experimental Additions", "0.1.8")
> NameError: name 'registerAddition' is not defined
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.0

**Comment by DatCaptainHorse** [comment]
You closed the issue so I assume you noticed that the Submod is outdated.
