### ISSUE TITLE
an update?

### ISSUE THREAD

**Issue by luckydog79** [CaptainHorse/MAS-Additions#13]
are you ever planning to update this?  or would maybe consider updating it?

**Comment by DatCaptainHorse** [comment]
Hey!

I started, well.. attempted updating this submod half-a-year ago but as you may see that fell quite short..

However very recently there has been a big change in my life situation and I feel very energetic, these past few days I've been working hard on the underlying engine that powers MAS-Additions. Once I get the important stuff fixed up on that side (such as Python scripting) I'll look into updating and fixing this submod here.

I cannot give a timeframe however, maybe I'll write an update here once I get to it and/or it's done.

**Comment by luckydog79** [comment]
Ok, I appreciate it.

**Comment by DatCaptainHorse** [comment]
Update: Linux support has been added and MIDI support has been updated.
Face Detection and Recognition is mostly updated but I'll need to write an API for others to be able to use it as well. I expect updated version to be released next week if testing doesn't show any issues.

**Comment by Cloverhood** [comment]
> Update: Linux support has been added and MIDI support has been updated.
> Face Detection and Recognition is mostly updated but I'll need to write an API for others to be able to use it as well. I expect updated version to be released next week if testing doesn't show any issues.

Its awesome that this is finally getting updated!

**Comment by DatCaptainHorse** [comment]
A new 1.0 pre-release has been added to the [releases page](https://github.com/CaptainHorse/MAS-Additions/releases/tag/1.0-pre).

If any of you are going to try it, please report any issues you come across.

NOTES:
The pre-release isn't quaranteed to work without problems.
Console showing what is happening is not hidden, which can be immersion breaking.
I haven't been able to test Linux running MAS yet (only binary functions), the package is there however if you wish to try it.

**Comment by luckydog79** [comment]
Cool, a submod I've wanted to see since day one is up

**Comment by Cloverhood** [comment]
Everything is working well so far, will update you if any bugs and glitches.

**Comment by Cloverhood** [comment]
super glad this received an update.

**Comment by DatCaptainHorse** [comment]
[1.0 pre-release 2 is out.](https://github.com/CaptainHorse/MAS-Additions/releases/tag/1.0-pre2)
This is mostly bugfixes, if you have had no issues so far there is no need to update yet.

**Comment by DatCaptainHorse** [comment]
New pre-release is out: https://github.com/CaptainHorse/MAS-Additions/releases/tag/1.0-pre3

It's a bigger update, meaning it can have new bugs or issues.
Changes are listed in the releases page but most major changes would be:

Monika's memory of what you look like has been improved
Monika can tell you to turn on some lights if it's too dark
Binary CPU use is lowered by a lot

**Comment by LeoSuzaku** [comment]
this one is cool too im gonna give it a shot (totally backing up the persistent first tho)

**Comment by luckydog79** [comment]
Yeah this submod is great

**Comment by DatCaptainHorse** [comment]
New pre-release: https://github.com/CaptainHorse/MAS-Additions/releases/tag/1.0-pre4

Mainly some bugfixes, hopefully fixing infinite preparation for some.. 
Also now everything comes included in a single package, share your feedback if this feels too bloaty in which case I need to find some good release method, making invidual packages myself is time consuming.

**Comment by DatCaptainHorse** [comment]
Hopefully the last pre-release: https://github.com/CaptainHorse/MAS-Additions/releases/tag/1.0-pre5

Added an option for keeping webcam on or only during use, so if you keep MAS open at night that little LED won't blind you anymore.
Detection method has been renamed to Recognition method and the options are better explained (also added Both as an option)
API for other submods to use should be stable for now. I've written some partial documentation in the wiki that I'll have to update once I have time.

I'd love to hear if this pre-release is working fine for everyone using the submod. If no issues pop up it might be proper release worthy.

Update/Edit: I'll be waiting for the next MAS update before dropping Additions 1.0 release, as next MAS version will have breaking piano changes I'll need to fix. For now the pre-release version seems to be working fine enough.

**Comment by DatCaptainHorse** [comment]
Closing, there's been few updates but this project is mostly on life-support until something happens.
