### ISSUE TITLE
Monika can't see me.

### ISSUE THREAD

**Issue by LeoSuzaku** [CaptainHorse/MAS-Additions#14]
I let her access my webcam, and she seems to be able to just fine (by the indicator light) but she told me something went wrong. Does anyone have an idea of what could have happened? I could try my best to provide information if need be about my specific Monika.

**Comment by LeoSuzaku** [comment]
was a one-time error it seems, Monika can see me now

**Comment by DatCaptainHorse** [comment]
Just in case can you tell me the specs of your computer? If that happened during first time only it may have been due to Monika not waiting long enough and I'll need to raise that time.
