### ISSUE TITLE
Not much of an issue to me personally, but...

### ISSUE THREAD

**Issue by LeoSuzaku** [CaptainHorse/MAS-Additions#15]
Would it be possible to add it/its pronouns? Totally okay if you can't, I completely understand, but I would appreciate if it were possible.

**Comment by DatCaptainHorse** [comment]
Can you specify where? I've tried to write everything as neutral as I can, but I may have missed something.

**Comment by LeoSuzaku** [comment]
> Can you specify where? I've tried to write everything as neutral as I can, but I may have missed something.

just realized i put this for the wrong mod author. terribly sorry. your mod words beautifully as of now. have a nice rest of your day.
