### ISSUE TITLE
Unrecoverable error when using piano

### ISSUE THREAD

**Issue by MoonlightGriffon** [CaptainHorse/MAS-Additions#16]
So, I was using the most resent prerelease. However when I tried playing the piano game the an error occured, after I ignored it and the next error that occured I was left in a gamestate where screenshots don't work as the piano game has disabled them but where there are no piano sprites on screen including the quit sprite.
This could be a result of me not having a midi keyboard on my computer.

**Comment by DatCaptainHorse** [comment]
Not a result of not having MIDI keyboard as the code handles the case where one doesn't exist. 

The pre-release of MAS has made changes to how Piano sprites are loaded and how it works, thus the incompatibility.

For now you can remove `MIDIsupport.rpy` to remove that submod until new MAS version is released and the submod updated (I'll also separate the Submods so it's not all bundled together).

**Comment by DatCaptainHorse** [comment]
Closing as fixed
