### ISSUE TITLE
few issues

### ISSUE THREAD

**Issue by Cdino11** [CaptainHorse/MAS-Additions#17]
the facial reorganization says not ready after a few hour, only one option can be changed, and only one click; to change any other option or the one you just clicked on you need to restart the game
 
im on a windows 10 laptop

**Comment by DatCaptainHorse** [comment]
Thanks for taking the time to write an issue and trying the pre-release version, it helps a ton as the project is quite complex for a Submod.

You should need to wait 5-10 seconds at most for facial recognition to be ready, hour means something ended up getting stuck and timeout failed to trigger.

Can you write down the steps you took to install the submod? For example:

1. Went to releases
2. Followed instructions on top-most (latest) releases
3. ...

**Comment by Cdino11** [comment]
1. I went to releases
2. Read the instructions
3. Clicked on the "download the repository" link and let it download
4. then I went to assets and downloaded the windows binary.zip
5. After they were done downloading, I went to my downloads folder and unzipped the folders
6. I went into the MAS Additions-Master folder first and copied the submods folder
7. I pasted the folder into my game folder, and made sure it ended up in my submods folder
8. I went back into the downloads folder and copied the submods folder from the windows.binary folder
9. I pasted that folder into my games folder again, I was asked to either override or skip 2 files (readme.txt and serverSim.py)
10. I let the files be overridden
11. I tried to startup but was given an error because I didnt have vcruntime140_1
12. After downloading and placing the file(vcruntime140_1) in the right spot I was able to start the game up

**Comment by Cathundred888** [comment]
Ya, I can't seem to get Monika to notice my face even though I downloaded the submod and it's there

> 1. I went to releases
> 2. Read the instructions
> 3. Clicked on the "download the repository" link and let it download
> 4. then I went to assets and downloaded the windows binary.zip
> 5. After they were done downloading, I went to my downloads folder and unzipped the folders
> 6. I went into the MAS Additions-Master folder first and copied the submods folder
> 7. I pasted the folder into my game folder, and made sure it ended up in my submods folder
> 8. I went back into the downloads folder and copied the submods folder from the windows.binary folder
> 9. I pasted that folder into my games folder again, I was asked to either override or skip 2 files (readme.txt and serverSim.py)
> 10. I let the files be overridden
> 11. I tried to startup but was given an error because I didnt have vcruntime140_1
> 12. After downloading and placing the file in the right spot I was able to start the game up

Ya, I can't seem to get her to recognize my face yet either even though the submod is 100% downloaded

**Comment by letoking77** [comment]
yeah same thing here but im on windows 10 PC (not sure if that matters or not)

**Comment by DatCaptainHorse** [comment]
Reply to @Cdino11
> After downloading and placing the file(vcruntime140_1) in the right spot I was able to start the game up

It's dangerous to download random DLL file off internet, as they can run any kind of code inside them.

Here is the proper link for the VC++ Redistributable: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

It's the *vc_redist.x64.exe* link listed below *Visual Studio 2015, 2017 and 2019*. I'll try to remember and add this to the release instructions list, I wrongly assumed most would have it installed as platforms like Steam install it for most games automatically.

&nbsp;

Reply to @Cathundred888 
Did you check the Submod menu, does it say "FDAR Status: Not ready" or something else? What is the status of MASM?

&nbsp;

Reply to @letoking77 
Can you also check the statuses in the Submod menu? Also Windows version shouldn't matter, I myself used Windows 10 and now Windows 11 Preview.

**Comment by letoking77** [comment]
It says for me FDAR is not ready. when I open MAS it a another popup says MASM has stopped working.
![Screenshot (73)](https://user-images.githubusercontent.com/69150491/132042791-5f74ecc1-d836-4b97-ba47-4ecc25b34aea.png)

**Comment by letoking77** [comment]
this is what it says when I open MASM.exe in MAS

**Comment by Cdino11** [comment]
@CaptainHorse my anti virus software and built in system defense didn't flag it, but since this is from Microsoft I want to have this version. Which should I download for that file?

**Comment by DatCaptainHorse** [comment]
@Cdino11 Here is a direct download link: https://aka.ms/vs/16/release/vc_redist.x64.exe

@letoking77 It helps that you opened the program manually to see the console, thank you. That error shouldn't happen so I'll push a "debugging" change for you to test tomorrow, been a long week and I need some sleep soon.

**Comment by Cathundred888** [comment]
> Reply to @Cdino11
> 
> > After downloading and placing the file(vcruntime140_1) in the right spot I was able to start the game up
> 
> It's dangerous to download random DLL file off internet, as they can run any kind of code inside them.
> 
> Here is the proper link for the VC++ Redistributable: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
> 
> It's the _vc_redist.x64.exe_ link listed below _Visual Studio 2015, 2017 and 2019_. I'll try to remember and add this to the release instructions list, I wrongly assumed most would have it installed as platforms like Steam install it for most games automatically.
> 
>  
> 
> Reply to @Cathundred888
> Did you check the Submod menu, does it say "FDAR Status: Not ready" or something else? What is the status of MASM?
> 
>  
> 
> Reply to @letoking77
> Can you also check the statuses in the Submod menu? Also Windows version shouldn't matter, I myself used Windows 10 and now Windows 11 Preview.

It's on, like the camera is on but the topics arent appearing

**Comment by Cdino11** [comment]
@CaptainHorse I installed the stuff from the link and dont get the error for startup, but the previous errors are still happening: face cam not ready, unable to change options more than once per game open and only one option can be changed per game open 

what can i do about that or was there anything wrong with how i installed it?

**Comment by DatCaptainHorse** [comment]
@Cathundred888 The topic should be under `Mod -> How do I look?`  and the first topic should begin once you start MAS with the Submod installed, you need to have atleast normal affection for them to show up (above 0 affection). I'll make some changes to the topic code during testing, maybe the event failed to trigger.

@Cdino11 You should have it installed correctly if MASM Status shows no issues. If you have the time in hour or so, can we move this to Discord as it's faster to work from there? *DatHorse#9516*

**Comment by Cdino11** [comment]
ill add you, but i dont have time tonight. its 2:30 am. thank you though

**Comment by Cathundred888** [comment]
> @Cathundred888 The topic should be under `Mod -> How do I look?` and the first topic should begin once you start MAS with the Submod installed, you need to have atleast normal affection for them to show up (above 0 affection). I'll make some changes to the topic code during testing, maybe the event failed to trigger.
> 
> @Cdino11 You should have it installed correctly if MASM Status shows no issues. If you have the time in hour or so, can we move this to Discord as it's faster to work from there? _DatHorse#9516_

Alright, I didn't find the topic so- Maybe I should wait until the topic shows up

**Comment by Cathundred888** [comment]
Like it says it's prepared, maybe I should give screenshots if it still doesnt work?

**Comment by DatCaptainHorse** [comment]
@Cathundred888 Ah, I think it's because you have already seen the original topic. I pushed a change that unlocks the "How do I look" topic by default (replace any files): https://github.com/CaptainHorse/MAS-Additions/archive/refs/heads/master.zip

**Comment by letoking77** [comment]
> @Cdino11 Here is a direct download link: https://aka.ms/vs/16/release/vc_redist.x64.exe
> 
> @letoking77 It helps that you opened the program manually to see the console, thank you. That error shouldn't happen so I'll push a "debugging" change for you to test tomorrow, been a long week and I need some sleep soon.

alright just tell me when and if you want to also move this to discord just let me know (sorry it took awhile to respond phone broke)

**Comment by DatCaptainHorse** [comment]
@letoking77 Discord would be preferred as it's faster to communicate that way, if you don't have time during the week due to timezone differences well look into next weekend.

**Comment by DatCaptainHorse** [comment]
Can't remember outcome of Discord, assuming this has been partially fixed atleast with new binaries.
