### ISSUE TITLE
How do I download???

### ISSUE THREAD

**Issue by Abc2557** [CaptainHorse/MAS-Additions#2]
So
Umm...
I'm very confused
So...
I'm just wanting to know how to download
…
Whatever this is...
…
…
I feel really stupid rn

**Comment by Abc2557** [comment]
Okay, *cough*, what I meant to say was, I want to know how to download this thing... I don't really know how to explain what I'm trying to say, but... I hope you understand me...
This seems like it'd be really cool and I want it in my MAS.

**Comment by DatCaptainHorse** [comment]
Go to the github repo page, then click Releases
![kuva](https://user-images.githubusercontent.com/14197772/64919424-11d80b80-d7b3-11e9-8f74-d39c98e2ada5.png)

after that, download one of the following packages you want
![kuva](https://user-images.githubusercontent.com/14197772/64919429-30d69d80-d7b3-11e9-9623-fa0e755ce71a.png)

then install as instructed in the Readme

**Comment by Abc2557** [comment]
Thanks for the quick reply!!!

**Comment by Abc2557** [comment]
I can't find the Readme

**Comment by Abc2557** [comment]
Are you talking about Readme_saftey.txt ?

**Comment by DatCaptainHorse** [comment]
Negative, readme is the text that shows on this page, down after file explorer
https://github.com/CaptainHorse/MAS-Additions

**Comment by Abc2557** [comment]
Thank you!
