### ISSUE TITLE
Hey, it's me again (Webcam not turning on)

### ISSUE THREAD

**Issue by LeoSuzaku** [CaptainHorse/MAS-Additions#23]
Installed the new update, now the webcam doesn't want to turn on at all.

**Comment by DatCaptainHorse** [comment]
Hey, for now see if the old version works: https://github.com/CaptainHorse/MAS-Additions/archive/refs/tags/1.0-pre5.zip

Current changes have some odd issues that I haven't gotten time yet to look deeply into.

**Comment by MiguelFitz** [comment]
well, im here again too, also as i say the old version didnt work, but ill try it again

**Comment by DatCaptainHorse** [comment]
Closing, pre-release 6 had some improvements and updated binaries which may have fixed this maybe? If not, new issue can be created.
