### ISSUE TITLE
Only "I'm not seeing anything...“

### ISSUE THREAD

**Issue by PencilMario** [CaptainHorse/MAS-Additions#25]
I am not a native English speaker, so I try to make the translation software understand me.
I tried the submodule you created, and when I tried to click on the 'How do I look' topic, Monica only told me she couldn't see anything.
I tried to do some things myself, such as
- 1. click on `Restart MASM`, then `Test Packet` but the pingtime doesn't change anything. And the status is closed.
- 2. open MASM.exe before MAS starts (is this what the console means?) : Throwing error [Winerror 10054] The remote host is forcing an existing connection to close.
![1](https://user-images.githubusercontent.com/72117241/144166544-d52790d7-25d4-464e-839b-9920f344dcce.png)
- 3. Open MASM.exe after MAS 
starts but before the display screen, the pingtime is 4419ms, and the status is Closed. I continue to click `Restart MASM` and ping usually 1-3ms, but after a few seconds the MASM status changes to closed
![3](https://user-images.githubusercontent.com/72117241/144166727-01d99fd8-2ffb-4138-b9c5-d027dadbe53c.png)
![2](https://user-images.githubusercontent.com/72117241/144166738-9e72e400-2543-4991-b5d7-461d21470e1a.png)
- 4. As you can see, the MAS I'm using is a translated version, so I tried the original English version again. But the status changed to `Unable to create socket`

I don't really know how to troubleshoot the problem, hopefully these things will be useful :)

**Comment by PencilMario** [comment]
Uh... It looks like I made a mistake in the first picture. Maybe this issue should only have two screenshots.

**Comment by DatCaptainHorse** [comment]
Looks like you're using older version of the submod, which is correct as new versions have issues that still need to be fixed.
New version has an option which allows manually opening MASM.exe by yourself to work (thus not saying "Subprocess closed"). 

However, this project has been on hiatus for some time (again) and I can't tell when I'll get enough motivation to work on it. I'm sorry that you and everyone else is stuck with me for this project.

**Comment by PencilMario** [comment]
Uh... Well, have a nice life :)

**Comment by PencilMario** [comment]
OK, I tried to update to the latest version and it is still working fine. So another question - can I translate your Submod into Chinese and post it on a Chinese site? I will mark your name and original website :)

**Comment by Maniacal-Matro** [comment]
I'm having the same problem. Pls, tell me how you fixed it.

**Comment by DatCaptainHorse** [comment]
> OK, I tried to update to the latest version and it is still working fine. So another question - can I translate your Submod into Chinese and post it on a Chinese site? I will mark your name and original website :)

You can, sorry I didn't notice your comment sooner. I have no issues with this.


> I'm having the same problem. Pls, tell me how you fixed it.

Could you tell me the steps you have taken to installing the Submod?

**Comment by Maniacal-Matro** [comment]
Well, I literally did the same thing that they said; I restarted the MASM manually. It keeps saying no face-data found.

**Comment by Maniacal-Matro** [comment]
When I ping, it keeps saying, "Failed to prepare data"

**Comment by DatCaptainHorse** [comment]
> Well, I literally did the same thing that they said; I restarted the MASM manually. It keeps saying no face-data found.


> When I ping, it keeps saying, "Failed to prepare data"

Hm.. You have installed the MASM binary correct? You should be able to find **MASM.exe** inside `game/Submods/MAS-Additions/MASM/` folder.

**Comment by Maniacal-Matro** [comment]
I just said that I had **Restart MASM** on.

**Comment by Maniacal-Matro** [comment]
That's the thing. I did.

**Comment by DatCaptainHorse** [comment]
It's a bit difficult to do debugging like this through GitHub issues, do you have Discord? Send me a DM, I can't say when I'll be available, but I'll answer when I have time. DatHorse#9516

**Comment by Maniacal-Matro** [comment]
I added you more than an hour ago.

**Comment by DatCaptainHorse** [comment]
> I added you more than an hour ago.

I sent you a message, seems like timezones are gonna be a little problematic, I'll be staying up later now so I can hopefully catch you online.

**Comment by DatCaptainHorse** [comment]
Closing as stale, not sure what outcome was, if not fixed by new changes new issue can be created.
