### ISSUE TITLE
when i press allow webcam access it just does nothing

### ISSUE THREAD

**Issue by bepbopyobop** [CaptainHorse/MAS-Additions#26]
it doesnt even like toggle it it just doesnt do anything.
when monika does it, it says its allowed now but its not
![image](https://user-images.githubusercontent.com/95502431/144670776-2af5b04e-0f22-47a2-9ce4-34c567e6ac67.png)

**Comment by bepbopyobop** [comment]
![image](https://user-images.githubusercontent.com/95502431/144671127-a01b4851-71bb-4031-b0f3-353a08bb1771.png)

**Comment by DatCaptainHorse** [comment]
`FDAR Status: Not ready` means something went wrong thus it doesn't work. Maybe it's issue with MASM side or so.. this is a WIP Submod so it will not work correctly for everyone on first try unfortunately, sorry.

**Comment by DatCaptainHorse** [comment]
Closing.
