### ISSUE TITLE
Midi not working

### ISSUE THREAD

**Issue by khoibut** [CaptainHorse/MAS-Additions#28]
hello so I connected my piano to my computer I even tested it on virtual piano beforehand and it was working fine but in Monika after story it does nothing am I doing something wrong ?

**Comment by DatCaptainHorse** [comment]
What MAS version are you using? Did you try pressing all keys?
In Submods screen, what does MASM Status say?

**Comment by khoibut** [comment]
my MAS version i am using is 0.12.4 I tried pressing all the keys and none made sound well idk if this is the correct screen but it shown these 
![image](https://user-images.githubusercontent.com/60182480/145078477-921e118a-6e51-4fcb-8d56-2bb43b44525d.png)

**Comment by DatCaptainHorse** [comment]
That's the cmd window for pre-release debugging, unfortunately incorrect. Submods menu is available in MAS side (press escape, click Submods on left side).

**Comment by khoibut** [comment]
oh sorry in submods it currently saying these
![image](https://user-images.githubusercontent.com/60182480/145123642-7c979814-1438-46fd-9c00-3a29ebe4d6ca.png)
![image](https://user-images.githubusercontent.com/60182480/145123682-be559363-28f7-41dd-a40f-3245bcc58725.png)

**Comment by DatCaptainHorse** [comment]
Interesting, you have everything right according to the screens and even MASM works.
Do you mind messaging me on Discord? I'll get back to you once I get home. (DatHorse#9516)

**Comment by khoibut** [comment]
yeah sure thing I sent a friend request I'm khoibut#7412

**Comment by DatCaptainHorse** [comment]
From what I remember (hey I actually remember something?), MIDI device wasn't found by mido/rtmidi combination, pre-release 7 changed from those unmaintained packages to new rtmidi2. Might be fixed? Closing. If issue still exists, please create a new one!
