### ISSUE TITLE
Laptop's webcam not dectected

### ISSUE THREAD

**Issue by KevM3333** [CaptainHorse/MAS-Additions#29]
Can someone help? I am playing on steam version of ddlc and the problem is for some reason my laptop's webcam isn't dectected by the submods and it said "FDAR Status : Not ready" and "FDAR State : Invalid state" like shown on the screenshot below which lead to Monika saying I had to allow her to access my laptop's webcam over and over again (and by the way I can't find the instruction file anywhere in the submod folder)
![Capture3](https://user-images.githubusercontent.com/97391028/148683710-0d27729a-9f00-475f-9207-88d8d3e3f0b3.PNG)
.

**Comment by DatCaptainHorse** [comment]
Could you also send a screenshot of what MASM status says? It's in Submods screen as well.

**Comment by KevM3333** [comment]
> Could you also send a screenshot of what MASM status says? It's in Submods screen as well.
![Capture4](https://user-images.githubusercontent.com/97391028/148687673-049f79e3-6c11-470c-bd3b-6f47d140052b.PNG)

Here you go.

**Comment by DatCaptainHorse** [comment]
It's not finding the MASM binary, as told by "MASM Status: Path not found". Did you remember to install the binary from releases section as well?

**Comment by KevM3333** [comment]
> It's not finding the MASM binary, as told by "MASM Status: Path not found". Did you remember to install the binary from releases section as well?

No, all i did was extract the zip file and then put "MAS Additions" folder in the submod folder at the ddlc mas. if that's the problem will you please tell me how do that step by step?

**Comment by DatCaptainHorse** [comment]
The releases tab (https://github.com/CaptainHorse/MAS-Additions/releases) contains the instructions.
You can skip the `First, download the Source code (zip), it includes all MAS scripts required.` step as you've already done that.

**Comment by KevM3333** [comment]
> The releases tab (https://github.com/CaptainHorse/MAS-Additions/releases) contains the instructions. You can skip the `First, download the Source code (zip), it includes all MAS scripts required.` step as you've already done that.

okay it's SOLVED thanks for helping you're a legend ;)
