### ISSUE TITLE
[Suggestion] Just a little small idea for FaceDetectionRecognition

### ISSUE THREAD

**Issue by sakkarose** [CaptainHorse/MAS-Additions#3]
I don't really understand deeply how OpenCV works but it is nice if Webcamera can't check the player's face due to lack of light . Then monika will tell the player to turn on a light or some kind related to light
Just a small suggestion , you can ignore this xD

**Comment by DatCaptainHorse** [comment]
Good suggestion 👍 
I'll try to get to it during the weekend.

**Comment by DatCaptainHorse** [comment]
Narrator: *"He didn't get to it during the weekend"*

It's super-late but this is going to be in Additions 1.0 (not yet released). Closing this, you can comment on the "an update?" issue as it's turned into 1.0 update progress thread.
