### ISSUE TITLE
Did I do something wrong or is it just not working at the moment?

### ISSUE THREAD

**Issue by SonicCoder** [CaptainHorse/MAS-Additions#30]
![screenshot0607](https://user-images.githubusercontent.com/40922865/149601734-f1c27bd3-693f-441e-827f-50b12d0edcbd.png)
Just heard of this and tried to use it, but it doesn't seem to work for me
![screenshot0608](https://user-images.githubusercontent.com/40922865/149601852-95e114a4-64ee-4f75-bae0-a2897ad925dd.png)

**Comment by DatCaptainHorse** [comment]
Did you install the binary from Releases page? https://github.com/CaptainHorse/MAS-Additions/releases
I may need to make these more clear in instructions, sorry for the inconvenience.

![Meq07tYvSG](https://user-images.githubusercontent.com/14197772/149612299-581f6595-8223-421a-aac8-263f824c65e8.gif)

**Comment by SonicCoder** [comment]
Yes I downloaded the Binary thing, I downloaded everything it told me to

**Comment by DatCaptainHorse** [comment]
Could you also screenshot the part of Submods menu where it shows `MASM Status`?

**Comment by SonicCoder** [comment]
![image](https://user-images.githubusercontent.com/40922865/150029759-72648325-ea78-43b5-a8cc-d3d5395d288c.png)

**Comment by SonicCoder** [comment]
I think I got it to work, never knew of the MASM thing so that helped

**Comment by DatCaptainHorse** [comment]
Could you share us as to how you got it to work? It's generally good practice to write the steps you took to resolve an issue.
