### ISSUE TITLE
Webcam not working

### ISSUE THREAD

**Issue by BrandiBlitz** [CaptainHorse/MAS-Additions#31]
Heya, I downloaded the MAS additions submod and the webcam feature is not working. Something about FDAR being invalid. I’m on a MacBook running Windows10 via bootcamp partition.

Also, your discord PMs block people who aren't sharing the same server as you.

Edit: is there a way to give camera access or no?

**Comment by DatCaptainHorse** [comment]
Closing, resolved in Discord (ages ago, doing some clean up on Issues)
