### ISSUE TITLE
[BUG] FDAR State is invalid, MAS cannot access webcam (NOT AN ARM CPU)

### ISSUE THREAD

**Issue by coder-incognito** [CaptainHorse/MAS-Additions#33]
FDAR State: Invalid state in MAS

Windows 11
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
System type	64-bit operating system, x64-based processor

It's pretty much like the first issue posted on this repo but I use an x64 CPU, not ARM. I went through that thread and just to make sure allowed both DDLC and MASM through the firewall, though they weren't even listed there, meaning I had to manually add them. The only antivirus software I have is the standard windows defender. My webcam does work, I did check to make sure.
Might as well also mention that initially MASM wouldn't launch with the error of a missing python3.dll. I nabbed the .dll file from somewhere and put it in the same directory as the executable, after which it did execute, and we arrived at the problem of the webcam not being detected. Maybe it has something to do with that? Thought I'd mention it too. Thanks!

**Comment by DatCaptainHorse** [comment]
Hello!

It seems I forgot to include the extra DLL file python needs with the Windows binaries 😅 
I'll let you know when I have fixed that!

**Comment by coder-incognito** [comment]
> Hello!
> 
> It seems I forgot to include the extra DLL file python needs with the Windows binaries 😅 I'll let you know when I have fixed that!

Ah understandable mistake. Can't wait to try it out then! Hopefully it'll detect the camera haha

**Comment by DatCaptainHorse** [comment]
Took a bit since I've been busy with other things, anyhow if you head to the latest pre-release [here](https://github.com/DatCaptainHorse/MAS-Additions/releases/tag/1.0-pre7), I updated the Windows binaries to include the missing DLL, hopefully that helps!

If you come across other issues, like FDAR state still being reported as invalid, I ask for your patience as I'll be rewriting this mod once Monika After Story updates to newer Ren'Py version 🙂

**Comment by coder-incognito** [comment]
> Took a bit since I've been busy with other things, anyhow if you head to the latest pre-release [here](https://github.com/DatCaptainHorse/MAS-Additions/releases/tag/1.0-pre7), I updated the Windows binaries to include the missing DLL, hopefully that helps!
> 
> If you come across other issues, like FDAR state still being reported as invalid, I ask for your patience as I'll be rewriting this mod once Monika After Story updates to newer Ren'Py version 🙂

@DatCaptainHorse Thanks for the fix! To update you, turns out that the status was invalid due to some misplacing of script files by me, so that's totally on me. My apologies for that. But yep now it works out of the box as long as you place the scripts and binaries in the right places, at least the webcam portion of your submod. I can't comment on the MIDI portion since I don't have a MIDI device that I could plug in. But other than that I'd say the windows binaries and scripts are working perfectly for the webcam stuff!
