### ISSUE TITLE
MASM not appearing to function correctly

### ISSUE THREAD

**Issue by Funtimef01** [CaptainHorse/MAS-Additions#36]
Whenever I try to run the MASM.exe file, it stops at an error. Some help in fixing the issue or at least knowledge as to what is going on would be much appreciated, thank you. The error should be shown in the attached image.
![Screenshot (403)](https://user-images.githubusercontent.com/102770504/204992137-ae6bc7b6-f1f8-4852-870d-88445bf152dd.png)

**Comment by DatCaptainHorse** [comment]
Could be AV blocking the creation of localhost port, but I recommend waiting for a rewrite of these submods as early next year MAS will be getting a big update relating to submods and Ren'Py 🙂

**Comment by Funtimef01** [comment]
Alright, thank you. If I can't get it working sometime today, I'll just leave it for when the migration happens.
