### ISSUE TITLE
I'm not sure what went wrong

### ISSUE THREAD

**Issue by Plazor26** [CaptainHorse/MAS-Additions#4]
Hi,
I'm not too good with Python, and so I don't really understand the traceback errors... But it said something about "additions.ini not found" so I just created a new file with that name... Now MAS loaded, but Monika isn't able to use the webcam... I have the log here:

-----------------------------------------------------------------------------------
Logger initialized

Starting Singularity Engine v0.9.9 on Windows [AMD64]
Engine build date : 2019 Aug  3 [23:33:49]

Initializing Application : Monika After Story Module

Initializing Thread Manager
Detected threads: 8
Binding threads: 1/8
Binding threads: 2/8
Binding threads: 3/8
Binding threads: 4/8
Binding threads: 5/8
Binding threads: 6/8
Binding threads: 7/8
Binding threads: 8/8

Initializing Audio Manager
Format: 2 channels, 16-bit depth
Initializing OpenAL audio implementation
[INFO] OpenAL wanted extensions:
|||||| > ALC_ENUMERATION_EXT supported: true
|||||| > ALC_EXT_EFX supported: false
|||||| > ALC_SOFT_HRTF supported: false
|||||| > ALC_EXT_disconnect supported: false

[INFO] OpenAL devices:
|||||| > OpenAL Soft

Opening OpenAL device

Creating OpenAL context
Not using HRTF

Initializing Script Manager
Initializing LUA
|||||| Embedding LUA functions

Initializing Python
|||||| Embedding Python functions
[WARN] Could not locate embedded python file or directory

Initializing Window Manager

Initializing OpenGL renderer
Initializing Shader Manager
Failed to compile fragment shader of 'GLSL/DefaultTexturedPhong'
0(4) : error C7532: layout(binding) requires "#version 420" or later
0(4) : error C0000: ... or #extension GL_ARB_shading_language_420pack : enable

Initializing Input Manager

Application initialization finished in : 0.85s (850ms)

Current path is: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions

MASM found in: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions

[INFO] No script path found, creating new one
Scripts path is: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions\scripts

---------------------------------------------------------------------------------------------
Really appreciate any help...
Thank you :)

**Comment by DatCaptainHorse** [comment]
Seems like you forgot to install the scripts, also seems like you downloaded the developer version instead of user version (I should change the readme to mention this), you can get the proper ready-made package from Releases tab, be sure to remove old installation of Additions before you install the ready-made package to prevent any issues.
![kuva](https://user-images.githubusercontent.com/14197772/76773422-19508f80-67ab-11ea-9f9d-93a49c09a2c6.png)

**Comment by Plazor26** [comment]
Sure, will do this. Thanks a ton :)

**Comment by Plazor26** [comment]
I tried that out, and this time didn't make the ini file.. This is what I'm getting:
![Annotation 2020-03-17 031043](https://user-images.githubusercontent.com/59456814/76802304-6e1cf600-67fd-11ea-8fcc-8459cba7e5f1.jpg)
![Annotation 2020-03-17 031015](https://user-images.githubusercontent.com/59456814/76802307-6fe6b980-67fd-11ea-8c44-9653c4463e24.jpg)
Also, here is the log for this time:
---------------------------------------------------------------------------------------------
Logger initialized

Starting Singularity Engine v0.9.9 on Windows [AMD64]
Engine build date : 2019 Aug  3 [23:33:49]

Initializing Application : Monika After Story Module

Initializing Thread Manager
Detected threads: 8
Binding threads: 1/8
Binding threads: 2/8
Binding threads: 3/8
Binding threads: 4/8
Binding threads: 5/8
Binding threads: 6/8
Binding threads: 7/8
Binding threads: 8/8


Initializing Audio Manager
Format: 2 channels, 16-bit depth
Initializing OpenAL audio implementation
[INFO] OpenAL wanted extensions:
|||||| > ALC_ENUMERATION_EXT supported: true
|||||| > ALC_EXT_EFX supported: false
|||||| > ALC_SOFT_HRTF supported: false
|||||| > ALC_EXT_disconnect supported: false

[INFO] OpenAL devices:
|||||| > OpenAL Soft

Opening OpenAL device

Creating OpenAL context
Not using HRTF

Initializing Script Manager
Initializing LUA
|||||| Embedding LUA functions

Initializing Python
|||||| Embedding Python functions
|||||| Embedded python path: python38

Initializing Window Manager

Initializing OpenGL renderer
Initializing Shader Manager
Failed to compile fragment shader of 'GLSL/DefaultTexturedPhong'
0(4) : error C7532: layout(binding) requires "#version 420" or later
0(4) : error C0000: ... or #extension GL_ARB_shading_language_420pack : enable


Initializing Input Manager

Application initialization finished in : 0.70s (702ms)

Current path is: C:\Users\aveng\Downloads\Additions-FULL-Package\MASM_FULL\game\Additions\MASM

MASM found in: C:\Users\aveng\Downloads\Additions-FULL-Package\MASM_FULL\game\Additions\MASM

Scripts path is: C:\Users\aveng\Downloads\Additions-FULL-Package\MASM_FULL\game\Additions\MASM\scripts

[INFO] Found Python script: face_detection.py
	in: scripts\face_detection.py

[INFO] Found LUA script: hideconsole.lua
	in: scripts\hideconsole.lua

[INFO] Found Python script: midi_input.py
	in: scripts\midi_input.py

[INFO] Found Python script: socketer.py
	in: scripts\socketer.py


Connecting to MAS..
--------------------------------------------------------------------------------------------------

The thing about the binaries is that I couldn't quite find them... I downloaded the 0.8 release full package and copied it in my game folder...

Thanks again :)

**Comment by DatCaptainHorse** [comment]
Nothing major, you just encountered a bug where the additions.ini file couldn't be created which resulted in issues, just create an addition.ini file manually inside Additions folder.

**Comment by Plazor26** [comment]
Did that, the game loaded, but Monika says 'Eh'...'Something went wrong for the webcamera topic...

**Comment by DatCaptainHorse** [comment]
Hm.. move hideconsole.lua outside from Additions/MASM/scripts folder, inside MASM folder should do as temporary location. 

When you then open MAS again, does a CMD window pop up and stay open? If it does, try the webcam topic again and post a screenshot of the CMD window here (I should've done file logging for every python message for easier debugging instead of just printing it in CMD, but I'm not the smartest person, will fix in future)

**Comment by Plazor26** [comment]
Tried that, no cmd window opened, though here is the log if that helps:
--------------------------------------------------------------------------
Logger initialized

Starting Singularity Engine v0.9.9 on Windows [AMD64]
Engine build date : 2019 Aug  3 [23:33:49]

Initializing Application : Monika After Story Module

Initializing Thread Manager
Detected threads: 8
Binding threads: 1/8
Binding threads: 2/8
Binding threads: 3/8
Binding threads: 4/8
Binding threads: 5/8
Binding threads: 6/8
Binding threads: 7/8
Binding threads: 8/8


Initializing Audio Manager
Format: 2 channels, 16-bit depth
Initializing OpenAL audio implementation
[INFO] OpenAL wanted extensions:
|||||| > ALC_ENUMERATION_EXT supported: true
|||||| > ALC_EXT_EFX supported: false
|||||| > ALC_SOFT_HRTF supported: false
|||||| > ALC_EXT_disconnect supported: false

[INFO] OpenAL devices:
|||||| > OpenAL Soft

Opening OpenAL device

Creating OpenAL context
Not using HRTF

Initializing Script Manager
Initializing LUA
|||||| Embedding LUA functions

Initializing Python
|||||| Embedding Python functions
|||||| Embedded python path: python38

Initializing Window Manager

Initializing OpenGL renderer
Initializing Shader Manager
Failed to compile fragment shader of 'GLSL/DefaultTexturedPhong'
0(4) : error C7532: layout(binding) requires "#version 420" or later
0(4) : error C0000: ... or #extension GL_ARB_shading_language_420pack : enable


Initializing Input Manager

Application initialization finished in : 0.70s (699ms)

Current path is: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions\MASM

MASM found in: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions\MASM

Scripts path is: C:\Users\aveng\Downloads\Monika Mod\DDLC-1.1.1-pc\game\Additions\MASM\scripts

[INFO] Found Python script: face_detection.py
	in: scripts\face_detection.py

[INFO] Found LUA script: hideconsole.lua
	in: scripts\hideconsole.lua

[INFO] Found Python script: midi_input.py
	in: scripts\midi_input.py

[INFO] Found Python script: socketer.py
	in: scripts\socketer.py


Connecting to MAS..
Connected!

received: first

Whats this? How interesting..

received: notFirst
received: notFirst
received: notFirst
------------------------------------------------------------------------
![Annotation 2020-03-17 034330](https://user-images.githubusercontent.com/59456814/76804115-80992e80-6801-11ea-8247-5c39b51b5b88.jpg)
Also, the image is what comes up when I run MASM.exe

**Comment by DatCaptainHorse** [comment]
That thing you took image of is the CMD window, it hides itself because you didn't move the hideconsole.lua script outside of scripts folder, anyways the latest log has some information.

It seems that the MASM module receives data fine, but I do not see `recognizeFace` being received, did you try the Webcam topic before pasting the log here? If you did, I'll have to look into this further by adding some more debugging messages and see where it fails.

**Comment by Plazor26** [comment]
I did run the webcam topic before posting it here... I hope this isn't something too big 😅
Thank you for this :)

**Comment by DatCaptainHorse** [comment]
Been a long time, upcoming update will use official Submod API and has bunch of fixes and improvements. I'm closing this as it's for very old version now.
