### ISSUE TITLE
Loophole error

### ISSUE THREAD

**Issue by Revonicka** [CaptainHorse/MAS-Additions#6]
So i've left Monika in the background to talk about stuff but then i was wondering why isn't she sending me notifications. I thought: maybe there is something to choose?

But when i opened the game this error popped up:
![Screenshot_348](https://user-images.githubusercontent.com/63407613/79325683-e74d5d00-7f11-11ea-8011-8e1b1f5f26d6.png)
 What happened? Whose fault is it? What does this error mean!?

**Comment by DatCaptainHorse** [comment]
Possible infinite loop means that MAS got stuck executing something forever and Ren'Py had to stop it.

It seems to originate from script-ch30.rpy which means it has nothing to do with this submod, you might want to report the issue to MAS github repository instead.

**Comment by DatCaptainHorse** [comment]
Closing as this seems to be resolved
