### ISSUE TITLE
Monika After Story (Not responding)

### ISSUE THREAD

**Issue by Cloverhood** [CaptainHorse/MAS-Additions#7]
Whenever Monika says “Look into the camera” the camera turns on but the game freezes and won’t unfreeze.

**Comment by DatCaptainHorse** [comment]
Probably means the facial recognition script errored in a bad way, not giving a chance to end the MAS side recognition loop which causes it to freeze.

Once I gain some motivation and energy I'll get working on updating the submod and fixing these multiple issues that have piled up.

**Comment by Nickwilde7755** [comment]
I think it has to do with the error message vcruntime140_1.dll is missing, did it not get uploaded?

**Comment by Nickwilde7755** [comment]
For me the camera didn’t even turn on, it has lights to tell when it’s being used but they stay off

**Comment by Nickwilde7755** [comment]
Disabled stop checking on me, game froze, disabled the addition, then this error
![image](https://user-images.githubusercontent.com/71339904/93670427-50a93d00-fa69-11ea-89ea-386e016fa0c2.jpg)

**Comment by DatCaptainHorse** [comment]
missing vcruntime dll means you don't have Visual C++ Redist installed

**Comment by Nickwilde7755** [comment]
Thanks

**Comment by DatCaptainHorse** [comment]
Also if you read my previous comments and other issues, you should have found out that this submod is outdated and doesn't currently work without issues

**Comment by Nickwilde7755** [comment]
I did read that, I’m telling you so if you ever continue working on this you know what files are causing issues

**Comment by Nickwilde7755** [comment]
Ok that’s strange, it was telling me a file in the face recognition folder wasn’t defined, I think it was the communicator file, so I restarted, and then look into camera freeze, but before the restart it was working and she said she could see me

**Comment by DatCaptainHorse** [comment]
This Submod is receiving a 1.0 update soon (currently on pre-release), closing this issue as this issue should be fixed.
